name: pindery
description: >- 
  Pindery is an Android and iOS based social network
  designed to join and organise parties, mainly geared
  towards low-level student events. Each user will have
  the possibility to generate a ‘new party’ or join
  already existing ones nearby.
homepage: https://aeeooto.gihtub.io/pindery/
version: 0.0.1-alpha0
authors:
  - Anna Tranquillini
  - Edoardo Debenedetti <edoardo.m.debenedetti@gmail.com>
  - Edoardo Ghignone

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^0.2.4
  cloud_firestore: ^0.7.3
  firebase_analytics: ^1.0.1
  firebase_storage: ^0.3.7
  image_picker: ^0.4.4
  image: ^2.0.2
  path_provider: ^0.4.1
  validator: ">=0.0.4 <0.1.0"
  firebase_auth: ^0.5.11
  google_sign_in: ^3.0.4
  cached_network_image: ^0.4.1
  connectivity: ^0.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  assets:
      - assets/img/beers.jpg
      - assets/img/classicalParty.jpeg
      - assets/img/movingParty.jpeg
      - assets/img/pasta.jpeg
      - assets/img/proseccoParty.jpg
      - assets/img/avatar.jpg
      - assets/img/kittens.jpeg
      - assets/img/logo_v_2_rosso.png
      - assets/img/beer_1.jpg
      - assets/img/beer_2.jpg
      - assets/img/beer_3.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
